export const QUERY_KEY = {
  COURSE: "COURSE",
  COURSE_MEMBERS: "COURSE_MEMBERS",
  TEAMS: "TEAMS",
  ACCOUNT: "ACCOUNT",
  ACADEMIC: "ACADEMIC",
  ACCOUNT_NO_PAGINATE: "ACCOUNT_NO_PAGINATE",
  COURSE_NO_PAGINATE: "COURSE_NO_PAGINATE",
  WORKSHOPS: "WORKSHOPS",
  WORKSHOPS_DETAILS: "WORKSHOPS_DETAILS",
  STATISTIC: "STATISTIC",
  LEADERBOARD: "LEADERBOARD",
  SYNC: "SYNC",
};
