export const API_URL = {
  LOGIN: "/auth/login",
  REFRESH_TOKEN: "auth/refreshToken",
  LOGOUT: "auth/logout",
  COURSE: "/courses",
  TEAMS: "/teams",
  ACCOUNT: "/users",
  ACCOUNT_NO_PAGINATE: "/accounts/no-pagination",
  COURSE_NO_PAGINATE: "/courses/no-paginate",
  WORKSHOPS: "/workshops",
  STATISTIC: "courses/statistic",
  WS_DASHBOARD: "/workshops/dashboard",
  SCORE: "/score",
  SYNC_COURSE: "/moodle/sync-data",
  ACADEMICS: "/academics",
  FACULTIES: "/faculties",
  MAGAZINE: "/magazines",
  ARTICLE: "/articles",
};
